language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_d09bdfb626fb_key -iv $encrypted_d09bdfb626fb_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mvn install:install-file -Dfile=stata-sfi.jar -DgroupId=com.stata.sfi 
  -DartifactId=sfi -Dversion=13 -Dpackaging=jar
